diplom/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include('rec_sys.urls')),
    path('admin/', admin.site.urls),
]

rec_sys/urls.py
from django.urls import path
from .views import *

app_name = 'rec_sys'
urlpatterns = [
    path('', search_recipes, name='search_first'),
    path('search/', search_recipes, name='search'),
    path('about/', view_about, name='about'),
    path('recipe/<int:recipe_id>/', view_recipe, name='view_recipe'),
    path('log_in/', log_in, name='log_in'),
    path('sign_in/', SignIn.as_view(), name='sign_in'),
    path('account/', view_account, name='account'),
    path('day_recipes/', view_day_recipes, name='day_recipes'),
]

rec_sys/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# blank - нельзя добавлять новые значения пустыми, null - не может быть пустого значения в БД


class Recipe(models.Model):
    title = models.CharField(max_length=200, unique=True, blank=False, null=False)
    ingredients = models.TextField(max_length=4000, unique=False, blank=False, null=False)
    directions = models.TextField(max_length=10000, unique=False, blank=False, null=False)
    description = models.TextField(max_length=4000, unique=False, blank=True, null=True)
    mean_rating = models.FloatField(default=0.0)
    fat = models.FloatField(unique=False, blank=True, null=True)
    calories = models.FloatField(unique=False, blank=True, null=True)
    protein = models.FloatField(unique=False, blank=True, null=True)
    sodium = models.FloatField(unique=False, blank=True, null=True)
    old_id = models.IntegerField()
    similar = models.TextField(max_length=10000, blank=True, null=True)

    def __str__(self):
        return ' - '.join([str(self.id), str(self.title), str(self.mean_rating), str(self.calories)])


class History(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    recipe = models.ForeignKey("Recipe", on_delete=models.CASCADE, blank=False, null=False)
    view_date = models.DateTimeField(blank=False, null=False, auto_now_add=True)

    def __str__(self):
        return ' - '.join([str(self.user), str(self.recipe), str(self.view_date)])


class AddedRecipes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    recipe = models.ForeignKey("Recipe", on_delete=models.CASCADE, blank=False, null=False)

    def __str__(self):
        return ' - '.join([str(self.user), str(self.recipe)])


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    recipe = models.ForeignKey("Recipe", on_delete=models.CASCADE, blank=False, null=False)
    rating = models.IntegerField()

    def __str__(self):
        return ' - '.join([str(self.user), str(self.recipe), str(self.rating)])


class Tag(models.Model):
    title = models.CharField(max_length=200, unique=True, blank=False, null=False)
    old_id = models.IntegerField()

    def __str__(self):
        return str(self.title)


class Category(models.Model):
    title = models.CharField(max_length=200, unique=True, blank=False, null=False)
    old_id = models.IntegerField()

    def __str__(self):
        return str(self.title)


class RecipesTags(models.Model):
    tag = models.ForeignKey("Tag", on_delete=models.CASCADE, blank=False, null=False)
    recipe = models.ForeignKey("Recipe", on_delete=models.CASCADE, blank=False, null=False)

    def __str__(self):
        return ' - '.join([str(self.tag), str(self.recipe)])


class RecipesCategory(models.Model):
    category = models.ForeignKey("Category", on_delete=models.CASCADE, blank=False, null=False)
    recipe = models.ForeignKey("Recipe", on_delete=models.CASCADE, blank=False, null=False)

    def __str__(self):
        return ' - '.join([str(self.category), str(self.recipe)])


class UserRecRecipes(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    recipe_list = models.TextField(max_length=2000, blank=True, null=True)

rec_sys/forms.py
from django import forms
from .models import *


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']

        widgets = {
            'first_name': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'email': forms.TextInput(attrs={'type': 'email', 'class': 'form-control', 'placeholder': 'name@example.com'}),
            'username': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'password': forms.TextInput(attrs={'type': 'password', 'class': 'form-control'})
        }

rec_sys/views.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.core.paginator import Paginator
from .models import *
from .forms import *


def search_recipes(request):

    search_input = ''
    if 'search_by_name' in request.GET:
        search_input = request.GET['search_input']
        recipes = Recipe.objects.filter(title__icontains=search_input).order_by('-mean_rating').values(
            'id', 'title', 'mean_rating')
        base_url = '/search/?search_input=' + search_input + '&search_by_name=&'
    else:
        if 'log_out_nav_but' in request.GET:
            logout(request)
        recipes = Recipe.objects.all().order_by('-mean_rating').values('id', 'title', 'mean_rating')
        base_url = '/search/?'
    paginator = Paginator(recipes, 20)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)

    return render(request, 'search.html', {'page': page, 'base_url': base_url, 'search_input': search_input})


def view_recipe(request, recipe_id):

    added = False
    recipe = Recipe.objects.get(id=recipe_id)
    rated = Rating.objects.filter(user=request.user.id, recipe=recipe_id).exists()
    if rated:
        recipe_rating = Rating.objects.get(user=request.user.id, recipe=recipe_id).rating
    else:
        recipe_rating = 0
    if request.user.is_authenticated:
        if request.method == 'POST':
            if 'add_recipe' in request.POST:
                added = True
                AddedRecipes.objects.create(user=request.user, recipe=recipe)
            elif 'del_recipe' in request.POST:
                added = False
                added_recipes = AddedRecipes.objects.filter(user=request.user.id, recipe=recipe_id)
                for item in added_recipes:
                    item.delete()
            elif 'rating_1' or 'rating_2' or 'rating_3' or 'rating_4' or 'rating_5' in request.POST:
                if rated:
                    user_rating = Rating.objects.get(user=request.user.id, recipe=recipe_id)
                else:
                    user_rating = Rating.objects.create(user=request.user, recipe=recipe, rating=0)
                    rated = True
                if 'rating_1' in request.POST:
                    user_rating.rating = 1
                elif 'rating_2' in request.POST:
                    user_rating.rating = 2
                elif 'rating_3' in request.POST:
                    user_rating.rating = 3
                elif 'rating_4' in request.POST:
                    user_rating.rating = 4
                elif 'rating_5' in request.POST:
                    user_rating.rating = 5
                user_rating.save()
                recipe_rating = user_rating.rating
        if AddedRecipes.objects.filter(user=request.user.id, recipe=recipe_id).exists():
            added = True
        if History.objects.filter(user=request.user, recipe=recipe).exists():
            h = History.objects.filter(user=request.user, recipe=recipe)
            for item in h:
                item.delete()
        else:
            history = History.objects.filter(user=request.user.id).order_by('view_date')
            if len(history) == 20:
                history[0].delete()
        History.objects.create(user=request.user, recipe=recipe)
    recipe = recipe.__dict__
    recipe['ingredients'] = recipe['ingredients'].split('00000000')
    recipe['directions'] = recipe['directions'].split('00000000')
    if recipe['description'] is None:
        recipe['description'] = 'This recipe has no description yet...'
    recipe['similar'] = recipe['similar'].split('$')
    similar_recipes = []
    for recipe_id in recipe['similar']:
        similar_recipes.append(Recipe.objects.get(id=recipe_id))
    return render(request, 'recipe_page.html', {'recipe': recipe,
                                                'added': added,
                                                'similar_recipes': similar_recipes,
                                                'rated': rated,
                                                'recipe_rating': recipe_rating})


def view_about(request):
    return render(request, 'about.html')


def view_account(request):
    f_recipes = Recipe.objects.filter(addedrecipes__user=request.user).order_by('-addedrecipes__id')
    h_recipes = Recipe.objects.filter(history__user=request.user).order_by('-history__view_date')
    return render(request, 'account.html', {'favourite_recipes': f_recipes, 'history_recipes': h_recipes})


def view_day_recipes(request):
    recipes_list = request.user.userrecrecipes.recipe_list.split('$')
    recipes = []
    for recipe_id in recipes_list:
        recipes.append(Recipe.objects.get(id=recipe_id))
    return render(request, 'day_recipes.html', {'recipes': recipes})


def log_in(request):

    if 'log_in_but' in request.GET:
        username = request.GET['username']
        password = request.GET['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = redirect('/search/')
            return response
        else:
            return render(request, 'login.html', {'login_error': True})
    return render(request, 'login.html', {'login_error': False})


class SignIn(View):

    def get(self, request):
        form_user = UserForm()
        return render(request, 'signin.html', context={'form_user': form_user, 'signin_error': False})

    def post(self, request):
        post_user = request.POST.copy()
        bound_form_user = UserForm(post_user)
        if bound_form_user.is_valid():
            new_user = bound_form_user.save()
            u = User.objects.get(username=new_user.username)
            u.set_password(new_user.password)
            u.save()
            rec_recipes_list = Recipe.objects.all().order_by('-mean_rating')[:50]
            UserRecRecipes.objects.create(
                user_id=u.id,
                recipe_list='$'.join([str(x) for x in rec_recipes_list.values_list('id', flat=True)])
            )
            login(request, u)
            response = redirect('/search/')
            return response
        return render(request, 'signin.html', context={'form_user': bound_form_user, 'signin_error': True})

rec_sys/templates/account.html
{% extends 'navbar.html' %}
{% block content %}

    </br>
    <div class="container">
        <h1 class="display-4">Профиль</h1>
        <br>
        <ul class="nav nav-tabs" id="account_tab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active text-dark" id="all_info" href="#all_info_content" role="tab" data-toggle="tab" aria-controls="all_info_content">
                    Информация
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" id="favourites" href="#favourites_content" role="tab" data-toggle="tab" aria-controls="favourites_content">
                    Избранное
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" id="history" href="#history_content" role="tab" data-toggle="tab" aria-controls="history_content">
                    История
                </a>
            </li>
        </ul>

        </br>

        <div class="tab-content">
            <div class="tab-pane active" id="all_info_content" role="tabpanel" aria-labelledby="all_info">
                <div class="form-group row">
                    <label for="username" class="col-sm-2 col-form-label">Логин</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="username" value="{{ user.username }}" disabled>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="first_name" class="col-sm-2 col-form-label">Имя</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="first_name" placeholder="not set" value="{{ user.first_name }}" disabled>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="last_name" class="col-sm-2 col-form-label">Фамилия</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="last_name" placeholder="not set" value="{{ user.last_name }}" disabled>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="email" class="col-sm-2 col-form-label">Почта</label>
                    <div class="col-sm-10">
                        <input type="email" class="form-control" id="email" placeholder="not set" value="{{ user.email }}" disabled>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="favourites_content" role="tabpanel" aria-labelledby="favourites">
                <p class="lead">Здесь рецепты, которые вам понравились 😋</p>
                {% for recipe in favourite_recipes %}
                    <a href="{% url 'rec_sys:view_recipe' recipe.id %}" class="list-group-item d-flex justify-content-between align-items-center list-group-item-action">
                        {{ recipe.title }}
                        <span class="badge badge-primary badge-pill">{{ recipe.mean_rating }}</span>
                    </a>
                {% endfor %}
                <br>
            </div>
            <div class="tab-pane" id="history_content" role="tabpanel" aria-labelledby="history">
                <p class="lead">Здесь рецепты, которые вы просматривали 🧐</p>
                {% for recipe in history_recipes %}
                    <a href="{% url 'rec_sys:view_recipe' recipe.id %}" class="list-group-item d-flex justify-content-between align-items-center list-group-item-action">
                        {{ recipe.title }}
                        <span class="badge badge-primary badge-pill">{{ recipe.mean_rating }}</span>
                    </a>
                {% endfor %}
                <br>
            </div>

        </div>

        <script>
            $('#search_tab a').on('click', function (e) {
                e.preventDefault()
                $(this).tab('show')
            })
        </script>
    </div>

{% endblock %}

rec_sys/templates/day_recipes.html
{% extends 'navbar.html' %}
{% block content %}

    <br>
    <h1 class="display-4">Рецепты дня</h1>
    <br>
    <p class="lead">🥰 Этот набор рецептов подобран специально для вас!</p>
    <p class="lead">
        Каждый день он будет обновляться в соответствии с вашими вкусовыми предпочтениями.
        Оценивайте, просматривайте и добавляйте в избранное рецепты, чтобы сделать рецомендации более точными.
    </p>
    {% for recipe in recipes %}
        <a href="{% url 'rec_sys:view_recipe' recipe.id %}" class="list-group-item d-flex justify-content-between align-items-center list-group-item-action">
            {{ recipe.title }}
            <span class="badge badge-primary badge-pill">{{ recipe.mean_rating }}</span>
        </a>
    {% endfor %}
    <br>

{% endblock %}

rec_sys/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% load static %}
      <link rel="shortcut icon" href="{% static "freshly-cook-meal-svgrepo-com.svg" %}" type="image/svg">
    <title>
      {% block title %} ZENGER | COOK {% endblock %}
    </title>

  </head>
  <body>

    <header>
      {% block header %} No header {% endblock %}
    </header>

    <main role="main" class="container">
      {% block content %}{% endblock %}
    </main>

    <main>
      {% block fluid_content %}{% endblock %}
    </main>




    <Optional JavaScript>
    <jQuery first, then Popper.js, then Bootstrap JS>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

rec_sys/templates/login.html
{% extends 'navbar.html' %}
{% block content %}

    <div class="container">
        <br>
        <h1 class="display-4">Вход</h1>
        <br>
        {% if login_error %}
            <small class="text-danger">Логин или пароль введены неверно!</small>
            <br><br>
        {% endif %}
        <form autocomplete="off" action="{% url 'rec_sys:log_in' %}" method="get" class="needs-validation" novalidate>
            <div class="form-group row">
                <label for="username" class="col-sm-1 col-form-label">Логин</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="username" name="username" required>
                    <div class="invalid-feedback">
                        Пожалуйста, введите логин.
                    </div>
                    <div class="valid-feedback">
                        Превосходно!
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <label for="password" class="col-sm-1 col-form-label">Пароль</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="password" name="password" required>
                    <div class="invalid-feedback">
                        Пожалуйста, введите пароль.
                    </div>
                    <div class="valid-feedback">
                        Замечательно!
                    </div>
                </div>
            </div>
            <br>
            <button type="action" class="btn btn-outline-secondary" name="log_in_but">Войти</button>
        </form>

        <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
            (function() {
                'use strict';
                window.addEventListener('load', function() {
                    // Fetch all the forms we want to apply custom Bootstrap validation styles to
                    var forms = document.getElementsByClassName('needs-validation');
                    // Loop over them and prevent submission
                    var validation = Array.prototype.filter.call(forms, function(form) {
                    form.addEventListener('submit', function(event) {
                        if (form.checkValidity() === false) {
                                event.preventDefault();
                                event.stopPropagation();
                            }
                            form.classList.add('was-validated');
                        }, false);
                    });
                }, false);
            })();
        </script>
    </div>

{% endblock %}

rec_sys/templates/navbar.html
{% extends 'index.html' %}

{% block header %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">

    {% load static %}
    <img src="{% static "freshly-cook-meal-svgrepo-com.svg" %}" width="35" height="35" class="d-inline-block align-top mr-sm-2" alt="" loading="lazy">
  <a class="navbar-brand" href="{% url 'rec_sys:search' %}">
      ZENGER | COOK
  </a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'rec_sys:search' %}">Поиск</a>
          </li>
          <li class="nav-item active">
            {% if user.is_authenticated %}
              <div class="nav-item active">
                  <a class="nav-link text-dark" href="{% url 'rec_sys:day_recipes' %}">Рецепты дня</a>
              </div>
            {% endif %}
          </li>
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'rec_sys:about' %}">О проекте</a>
          </li>
      </ul>
        {% if user.is_authenticated %}
          <div class="nav-item active">
              <a class="nav-link text-dark" href="{% url 'rec_sys:account' %}">Профиль</a>
          </div>
        {% endif %}
  {% if user.is_authenticated %}
      <div class="btn-group" role="group">
          <form action="{% url 'rec_sys:search' %}" method="get">
              <button type="action" class="btn btn-outline-secondary mr-sm-2" name="log_out_nav_but">Выйти</button>
          </form>
      </div>
  {% else %}
      <form action="{% url 'rec_sys:sign_in' %}" method="get">
          <button type="action" class="btn btn-outline-secondary mr-sm-2" name="sign_in_nav_but">Зарегистрироваться</button>
      </form>
      <form action="{% url 'rec_sys:log_in' %}" method="get">
          <button type="action" class="btn btn-outline-secondary my-10 my-sm-0" name="log_in_nav_but">Войти</button>
      </form>
  {% endif %}
  </div>
</nav>


{% endblock %}

rec_sys/templates/recipe_page.html
{% extends 'navbar.html' %}
{% block content %}

    <div class="container">
        <br>
        <h1 class="display-4">{{ recipe.title }}</h1>
        <br>
        {% if user.is_authenticated %}
            <div class="text-right mb-3">
                <form action="{% url 'rec_sys:view_recipe' recipe.id %}" method="post">
                    {% csrf_token %}
                    <div class="btn-group mr-2" role="group" aria-label="First group">
                        {% if rated and recipe_rating == 1 %}
                            <button type="action" class="btn btn-danger" name="rating_1" disabled>1</button>
                        {% else %}
                            <button type="action" class="btn btn-outline-secondary" name="rating_1">1</button>
                        {% endif %}
                        {% if rated and recipe_rating == 2 %}
                            <button type="action" class="btn btn-danger" name="rating_2" disabled>2</button>
                        {% else %}
                            <button type="action" class="btn btn-outline-secondary" name="rating_2">2</button>
                        {% endif %}
                        {% if rated and recipe_rating == 3 %}
                            <button type="action" class="btn btn-warning" name="rating_3" disabled>3</button>
                        {% else %}
                            <button type="action" class="btn btn-outline-secondary" name="rating_3">3</button>
                        {% endif %}
                        {% if rated and recipe_rating == 4 %}
                            <button type="action" class="btn btn-success" name="rating_4" disabled>4</button>
                        {% else %}
                            <button type="action" class="btn btn-outline-secondary" name="rating_4">4</button>
                        {% endif %}
                        {% if rated and recipe_rating == 5 %}
                            <button type="action" class="btn btn-success" name="rating_5" disabled>5</button>
                        {% else %}
                            <button type="action" class="btn btn-outline-secondary" name="rating_5">5</button>
                        {% endif %}
                    </div>
                    {% if added %}
                        <button type="action" class="btn btn-outline-secondary" name="del_recipe">Удалить из избранного</button>
                    {% else %}
                        <button type="action" class="btn btn-outline-secondary" name="add_recipe">Добавить в избранное</button>
                    {% endif %}
                </form>
            </div>
        {% endif %}
        <br>
        <p class="lead">{{ recipe.description }}</p>
        <br>

        <div class="accordion" id="accordionExample">
            <div class="card">
                <div class="card-header" id="headingOne">
                    <a class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        <div class="lead">Ингредиенты</div>
                    </a>
                </div>

                <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                    <div class="card-body">
                        <ul type="circle">
                            {% for ingredient in recipe.ingredients %}
                                <li class="lead">{{ ingredient }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header" id="headingTwo">
                    <a class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        <div class="lead">Способ приготовления</div>
                    </a>
                </div>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                    <div class="card-body">
                        <ul type="circle">
                            {% for direction in recipe.directions %}
                                <li class="lead">{{ direction }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    {% if user.is_authenticated %}
        <br>
        <h1 class="display-4">Вам также может понравиться</h1>
        <br>

        <div class="list-group">
            {% for recipe in similar_recipes %}
                <a href="{% url 'rec_sys:view_recipe' recipe.id %}" class="list-group-item d-flex justify-content-between align-items-center list-group-item-action">
                {{ recipe.title }}
                <span class="badge badge-primary badge-pill">{{ recipe.mean_rating }}</span>
                </a>
            {% endfor %}
            <br>
        </div>
    {% else %}
        <br>
        <p class="lead">Пожалуйста, зарегистрируйтесь или войдите для получения рекомендаций.</p>
        <br>
    {% endif %}

    </div>

{% endblock %}

rec_sys/templates/search.html
{% extends 'navbar.html' %}
{% block content %}

    </br>
        <div align="center">
            <h1 class="display-4">ZENGER | COOK</h1>
        </div>
    </br>
    <form action="{% url 'rec_sys:search' %}" method="get">
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Введите название рецепта..." aria-describedby="button-addon2" name="search_input" value="{{ search_input }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="action" name="search_by_name">Поиск</button>
            </div>
        </div>
    </form>
    <div class="list-group">
        {% for recipe in page.object_list %}
            <a href="{% url 'rec_sys:view_recipe' recipe.id %}" class="list-group-item d-flex justify-content-between align-items-center list-group-item-action">
                {{ recipe.title }}
                <span class="badge badge-primary badge-pill">{{ recipe.mean_rating }}</span>
            </a>
        {% endfor %}
        <br>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item">
                    <a class="page-link text-dark" href="{{ base_url }}page=1" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>

                {% for n in page.paginator.page_range %}
                    {% if page.number == n %}
                        <li class="page-item active">
                            <a class="page-link" href="{{ base_url }}page={{ n }}">{{ n }}</a>
                        </li>
                    {% elif n > page.number|add:-3 and n < page.number|add:3 %}
                        <li class="page-item">
                            <a class="page-link text-dark" href="{{ base_url }}page={{ n }}">{{ n }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                <li class="page-item">
                    <a class="page-link text-dark" href="{{ base_url }}page={{ page.paginator.num_pages }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>

        <br>
    </div>

    <script>
        $('#search_tab a').on('click', function (e) {
            e.preventDefault()
            $(this).tab('show')
        })
    </script>

{% endblock %}